service:
  name: simple-rock-paper-scissors

provider:
  name: aws
  runtime: nodejs6.10

functions:
  main:
    handler: ./.webpack/handler.simpleRPS
    events:
      - alexaSkill:
        appId: ${file(./config/secrets.yml):alexa.appId}
        enabled: true
