service:
  name: simple-rock-paper-scissors

provider:
  name: aws
  runtime: nodejs6.10
  profile: simple-rock-paper-scissors
  region: ap-northeast-1
  environment:
    ALEXA_APP_ID: ${file(./config/secrets.yml):alexa.appId}

functions:
  main:
    handler: index.handler
    events:
      - alexaSkill:
        appId: ${file(./config/secrets.yml):alexa.appId}
        enabled: true
